### ISSUE TITLE
No minions

### ISSUE THREAD

**Issue by virtualguy** [Lothiraldan/saltpad#114]
My minions list is empty but from the dashboard I can see there are 10 accepted keys, 4 keys refused, and 2 keys refused.

From the output of salt-key, there should be 29 accepted keys, 0 denied keys and 0 unaccepted keys.
1. Does one of the hover over labels need to change to unaccepted?
2. Is the lack of minions showing up due to an older version of the salt-api?

I am using cherrypi via wsgi in apache + SSL

salt --versions
Salt Version:
           Salt: 2015.8.3

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: debian 8.2
        machine: x86_64
        release: 4.1.5-x86_64-linode61
         system: debian 8.2

**Comment by TheBigBear** [comment]
@virtualguy, I am surprised you got saltpad working with cherrypi? 

I thought it's instructions say that only tornado will work for this new one page app saltpad ?

But it does show that you get at least some output even when using a master running at 2015.8.3.

**Comment by Lothiraldan** [comment]
I'm definitely not sure about rest_cherrypy supports, I will give it a try.

About the minions list that is empty, saltpad detects minions with test.ping results, try launching one manually on "*", it should works. Saltpad doesn't actually launch itself test.ping jobs, I'm not sure yet if it should, at which frequency, etc...
