### ISSUE TITLE
In the saltpad v1, the session (E.g session['user_token']) is cleared when I close the program. But in my program,the session of the  user_token is always there. I want to clear the session when I close the program. What shoud I do?

### ISSUE THREAD

**Issue by jandxfvr** [Lothiraldan/saltpad#141]
Help me !!
In the saltpad v1, the session (E.g session['user_token']) is cleared when I close the program and then run the program. But in my program,the session of the  user_token is always there. I want to clear the session when I close the program. What shoud I do?

E.g:
http://flask.pocoo.org/docs/0.10/quickstart/#sessions

**Comment by Lothiraldan** [comment]
By default, flask cookies should expire automatically when closing all the open tabs or the browser. Check `permanent` attribute on the session http://flask.pocoo.org/docs/0.10/api/#flask.session.permanent.

I'm not sure if it's a request for settings on saltpad or in your own program. Could you clarify the need please?

**Comment by jandxfvr** [comment]
Thanks for your reply.
I know that flask cookies will expire automatically when closing all the open tabs or the browser.
but I want to the cookies expires automatically when close the web server without closing browser.

It's a request for settings in my own program. 

using this code
http://flask.pocoo.org/docs/0.10/quickstart/#sessions

in index(), add "print session['username']"

add "app.run('127.0.0.1', 9000)" in the last row

1 run the web server
2 access '127.0.0.1:9000/login'
3 input '123', click 'login button', then the session['username'] is '123' in the stdout
3 close the web server without closing browser
4 run the web server without closing browser
5 access '127.0.0.1:9000'
6 The session['username'] is '123' in the stdout, but I want it will be 'None'

In saltpad v1, the session['user_token'] is None when closing and running the web server.

My English is so bad, Can you remember what i mean?

**Comment by Lothiraldan** [comment]
Ok right, there is no "official" way to do it but you can put this as configuration:

```
SECRET_KEY = os.urandom(24)
```

Which means it will generate a new SECRET_KEY each time the application restart and so existing cookies will be invalidated because of the new SECRET_KEY.

I've had no issues understanding your last message, it was clear.

I hope it will solve your needs, if so could you please close the issue?

**Comment by jandxfvr** [comment]
Yes, this is what I want, thank you very much.
