### ISSUE TITLE
Module build failed: ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by aditaa** [Lothiraldan/saltpad#148]
im getting errors wile running 
`npm run build`

it still seams to build the files but they do not work .... is it mabe a version issue ..... 

i want to try to build the git version and not the release version as i want the new feature from https://github.com/Lothiraldan/saltpad/pull/147 

any help would be great 

error log
http://pastebin.com/GUGn36Qc

**Comment by Lothiraldan** [comment]
Did you ran `npm install` first?

**Comment by aditaa** [comment]
yes `npm install` and `./node_modules/bower/bin/bower install` ran without errors

**Comment by aditaa** [comment]
if i try to load that dist this is the error in the browser console

```
vendors.js:1 Uncaught SyntaxError: Unexpected token <
app.js:1 Uncaught SyntaxError: Unexpected token <
```

**Comment by Lothiraldan** [comment]
I will try with an empty node_modules and tries to reproduce the error

**Comment by MisterTK** [comment]
For what it's worth...using a Windows system to setup the npm environment fails every time with a "Promise is not defined" error.  Setting up the npm environment completes successfully, and all appears to be healthy.  npm run build doesn't work.  Even when running "npm start" the page will launch, and it will login, then bomb out with a promise not defined error.  I beat my head against the wall, but couldn't get past it. I built a new ubuntu vm, and everything worked flawlessly.  Not sure if this is applicable, but that's my two cents.

**Comment by Lothiraldan** [comment]
Which node version do you use? According to https://github.com/webpack/css-loader/issues/144, you may have a too old node version

**Comment by aditaa** [comment]
i will try that and let you know

**Comment by aditaa** [comment]
ok so i updated node js to latest stable version and i no longer get the errors running `npm run build` but the end result is still the same

**Comment by aditaa** [comment]
it appears https://github.com/Lothiraldan/saltpad/pull/147 has it look for the files in ./static/ cp'ing the files there worked to fix the issue

**Comment by Lothiraldan** [comment]
Right, I forget to specify it in the changelog, sorry, will fix it

**Comment by Lothiraldan** [comment]
It is fixed now
