### ISSUE TITLE
Websocket connection error 1006

### ISSUE THREAD

**Issue by Ferbla** [Lothiraldan/saltpad#150]
Whenever I try to login to saltpad I receive this error.

> Websocket connection was abnormally closed, logout! Reason: , code: 1006

I have tested the local pam with the following command, and I get results.

> salt -a pam minion1 test.ping

Here is my settings.json file contents.
`{
    "API_URL": "192.168.3.50:8000",
    "SECURE_HTTP": false,
    "templates": {},
    "EAUTH": "pam",
    "FLAVOUR": "rest_cherrypy"
}`

Here is my salt-master rest_cherrypy settings.
`rest_cherrypy:
  disable_ssl: true
  port: 8000`

Here is my master information.

> salt --versions-report

> Salt Version:
>            Salt: 2015.8.8.2
> 
> Dependency Versions:
>          Jinja2: 2.7.2
>        M2Crypto: 0.21.1
>            Mako: Not Installed
>          PyYAML: 3.11
>           PyZMQ: 14.7.0
>          Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
>            RAET: Not Installed
>         Tornado: 4.2.1
>             ZMQ: 4.0.5
>            cffi: 0.8.6
>        cherrypy: 3.2.2
>        dateutil: 1.5
>           gitdb: 0.5.4
>       gitpython: Not Installed
>           ioflo: Not Installed
>         libgit2: Not Installed
>         libnacl: Not Installed
>    msgpack-pure: Not Installed
>  msgpack-python: 0.4.7
>    mysql-python: Not Installed
>       pycparser: 2.14
>        pycrypto: 2.6.1
>          pygit2: Not Installed
>    python-gnupg: Not Installed
>           smmap: 0.8.1
>         timelib: Not Installed
> 
> System Versions:
>            dist: centos 7.2.1511 Core
>         machine: x86_64
>         release: 3.10.0-229.7.2.el7.x86_64
>          system: CentOS Linux 7.2.1511 Core

Any thoughts on what could be up?

**Comment by Lothiraldan** [comment]
saltpad with rest_cherrypy flavour shouldn't try to use websocket but use sse instead, what version of saltpad did you tried?

**Comment by Ferbla** [comment]
I am using the latest version I believe. This is the command I ran to get it.

wget https://github.com/Lothiraldan/saltpad/releases/download/v0.2/dist.zip

**Comment by Lothiraldan** [comment]
I've just added the support for rest_cherrypy in the develop version, you'll need to wait for the next release which should happens soon.

**Comment by aditaa** [comment]
you could also use the development version of saltpad by following this instructions https://github.com/Lothiraldan/saltpad#hack-on-saltpad

**Comment by Lothiraldan** [comment]
@Ferbla I release yesterday a new version (v0.3) of saltpad which should support rest_cherrypy, please give it a try.

**Comment by gerbilizer** [comment]
Hi, I got the 1006 error too.

Master configuration:
rest_tornado:
  port: 5417
  host: 0.0.0.0
  disable_ssl: true
  websockets: True
  cors_origin: '*'
rest_cherrypy:
  port: 8080
  host: 0.0.0.0
  webhook_url: /hook

settings.json:
{
    "API_URL": "myserver:8080",
    "SECURE_HTTP": false,
    "templates": {
        "basic": {
            "description": "Basic template",
            "matcher": "glob",
            "target": "*",
            "moduleFunction": "test.fib",
            "arguments": {
                "num": 10
            }
        },

        "version": {
            "description": "Basic version",
            "matcher": "glob",
            "target": "Celeste",
            "moduleFunction": "test.version",
            "arguments": {}
        }
    },
    "EAUTH": "pam",
    "FLAVOUR": "rest_cherrypy",
    "PATH_PREFIX": "/"
}

Using salt 2015.8.8 (Beryllium) and ran a git clone for the code.

Am I doing something wrong?

**Comment by TripleRockGit** [comment]
@Lothiraldan , I have tried saltpad 0.3 release (with rest_cherrypy and saltstack 2015.8.8) . It still failed with this websocker error (saying WebSocket connection to 'ws://****/all_events/sdfde1d2423239643d2e2234895324af184945654' failed: Error during WebSocket handshake: Unexpected response code: 404)

**Comment by Lothiraldan** [comment]
@gerbilizer @TripleRockGit, the websocket error is "normal" considering that rest_cherrypy uses SSE instead WebSocket, the question is why saltpad tries to connect to the websocket endpoint even as you've set "rest_cherrypy" as the "FLAVOUR" setting.

Could you try running a debug command on your browser console?

```
window.store.get('settings')
```

It should show the loaded settings in order to be sure that saltpad recognize the "FLAVOUR" setting.

**Comment by TripleRockGit** [comment]
@Lothiraldan, output of the debug command on Chrome is like below (it's reformated for easy reading)
API_URL:"***:5417"
EAUTH:"pam"
FLAVOUR:"rest_cherrypy"
PATH_PREFIX:"/opt/saltpad/"
SECURE_HTTP:false
templates:Object
basic:Object
version:Object
__proto__:Object
__proto__:Object
__defineGetter__:__defineGetter__()
__defineSetter__:__defineSetter__()
__lookupGetter__:__lookupGetter__()
__lookupSetter__:__lookupSetter__()
constructor:Object()
hasOwnProperty:hasOwnProperty()
isPrototypeOf:isPrototypeOf()
propertyIsEnumerable:propertyIsEnumerable()
toLocaleString:toLocaleString()
toString:toString()
valueOf:valueOf()
get __proto__:get __proto__()
set __proto__:set __proto__()

**Comment by Ferbla** [comment]
I have updated to the latest version, and now I get "Network Error" when I try to authenticate

**Comment by mraky** [comment]
@Ferbla what was version, which was working ?

**Comment by Ferbla** [comment]
I installed the Pre-alpha 3.1, I have never been able to login

**Comment by Lothiraldan** [comment]
@Ferbla did you tried the debug command in the documentation to check if the login works on salt-api side?

Could you try to check the network tab in your browser to have more details about the source of the error?

**Comment by Ferbla** [comment]
@Lothiraldan After digging into the network tab I found I had misconfigured an option in the settings.json. I am now able to login. 

Thanks everyone for all your help

**Comment by mraky** [comment]
@blake,  can you share config please? I am facing same problem

**Comment by Ferbla** [comment]
@mraky This is my settings.json file now.

`{
    "API_URL": "192.168.3.50:8000",
    "SECURE_HTTP": false,
    "templates": {
        "version": {
            "description": "Basic version",
            "matcher": "glob",
            "target": "*",
            "moduleFunction": "test.version",
            "arguments": {}
        }
    },
    "EAUTH": "pam",
    "FLAVOUR": "rest_cherrypy",
    "PATH_PREFIX": "/"
}`

**Comment by mraky** [comment]
@blake could you please share also your master please ? (only relevant
parts ), thank you alot .

2016-05-03 20:37 GMT+03:00 Blake <notifications@github.com>:

**Comment by Ferbla** [comment]
@mraky Sure thing. We use rest_cherrypy, here is my configuration for that which is in my master config.

```
  rest_cherrypy:
  disable_ssl: true
  host: 192.168.3.50
  port: 8000
```

Here is an example of my external_auth configuration too.

```
external_auth:
  pam:
    ferbla:
    - .*
    - '@runner'
    - '@wheel'
```

Hope this helps
