### ISSUE TITLE
Typo: "bower" vs "browser"

### ISSUE THREAD

**Issue by guettli** [Lothiraldan/saltpad#152]
https://github.com/Lothiraldan/saltpad#hack-on-saltpad

> ./node_modules/bower/bin/bower install # install browser dependencies

I guess one "r" is missing or to much.

**Comment by Lothiraldan** [comment]
You're damn right sir!

**Comment by Lothiraldan** [comment]
Fixed!

**Comment by Lothiraldan** [comment]
Thank you for the issue
