### ISSUE TITLE
500 Interal Server Error with Vagrant

### ISSUE THREAD

**Issue by Foorack** [Lothiraldan/saltpad#165]
Downloaded Vagrant yesterday so I assume I use the latest version.
All I have done is cloning the repository and executed "vagrant up" in the vagrant folder.
Connecting to the server gives the following result:
![image](https://cloud.githubusercontent.com/assets/5008081/15148130/25df84cc-16c4-11e6-9b41-1f32e9de982b.png)

**Comment by Foorack** [comment]
Perhaps relevant logs:
`root@vagrant-ubuntu-trusty-64:/opt/saltpad-dev# cat /var/log/nginx/error.log
2016/05/10 13:14:04 [error] 7330#0: *1 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 10.0.2.2, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
2016/05/10 13:14:04 [error] 7330#0: *2 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 10.0.2.2, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/"
2016/05/10 13:14:18 [error] 7330#0: *3 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 10.0.2.2, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
2016/05/10 13:14:18 [error] 7330#0: *4 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 10.0.2.2, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/"
2016/05/10 13:35:41 [error] 1004#0: *1 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 10.0.2.2, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
2016/05/10 13:35:41 [error] 1004#0: *2 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 10.0.2.2, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/"
root@vagrant-ubuntu-trusty-64:/opt/saltpad-dev# cat /var/log/nginx/error.log
2016/05/10 13:14:04 [error] 7330#0: *1 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 10.0.2.2, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
2016/05/10 13:14:04 [error] 7330#0: *2 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 10.0.2.2, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/"
2016/05/10 13:14:18 [error] 7330#0: *3 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 10.0.2.2, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
2016/05/10 13:14:18 [error] 7330#0: *4 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 10.0.2.2, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/"
2016/05/10 13:35:41 [error] 1004#0: *1 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 10.0.2.2, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
`

**Comment by Lothiraldan** [comment]
Hi @Foorack, I usually use the docker compose environment to hack on saltpad, the docker environment should helps you test saltpad if you have access to docker and I will take a look at the vagrant environment to see what doesn't works.

**Comment by Foorack** [comment]
@Lothiraldan Thanks for the quick response. The docker build seems to be outdated and throw error on missing file "requirements.txt". Will try install this on a dev server instead.

**Comment by ninjada** [comment]
seeing same nginx 500 issue. nginx error log:

```
sudo cat /var/log/nginx/error.log
2016/05/30 03:52:39 [error] 7553#0: *1 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 10.0.2.2, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
2016/05/30 03:52:39 [error] 7553#0: *2 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 10.0.2.2, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/"
2016/05/30 03:52:48 [error] 7553#0: *3 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 10.0.2.2, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
2016/05/30 03:52:48 [error] 7553#0: *4 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 10.0.2.2, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/"
```

**Comment by Lothiraldan** [comment]
@Foorack, are you sure you use the latests version of the Docker file?

@ninjada, did you tries with the vagrant environment or the Docker one?

**Comment by ninjada** [comment]
error with vagrant

**Comment by Lothiraldan** [comment]
I will check it.

**Comment by jolting** [comment]
Here's the nginx site file.
```
server {
    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;

    root /opt/saltpad/;
    index index.html;

    location / {
            try_files $uri /index.html;
    }
}
```

If you're on master saltpad is installed is installed in `/opt/saltpad-dev` instead of `/opt/saltpad` and despite having an `index-prod.html` and an `index-dev.html` there isn't a `index.html`. I'm new to this, so I probably skipped a few steps.
