### ISSUE TITLE
salt 2016.11.1 with saltpad

### ISSUE THREAD

**Issue by grigorov** [Lothiraldan/saltpad#190]
Hi, i have a problem with saltpad with my saltstack.

```
salt-master --version
salt-master 2016.11.1 (Carbon)
salt-api --version
salt-api 2016.11.1 (Carbon)
salt-minion --version
salt-minion 2016.11.1 (Carbon)
```

Saltpad not compatible with salt-master 2016.11.x?

**Comment by Sjd-Risca** [comment]
Here the same. Can login, but the output rendering doesn't work at all (and also many other issues).

**Comment by PierreR** [comment]
I don't want to sound negative but this project looks dead. It is really a shame but not that surprising given the amount of open source salt ui projects that has followed the same path these last years.

I really understand that priorities and focuses changes a lot particularly in the open source personal space. Why I find disrespectful is the laziness of not clearly saying so. A simple line in the README saying "sorry dead project, please fork it and try to make it better. The foundation is sane and I am willing to help you while you take it over"

**Comment by nikdatrix** [comment]
Sanka ya dead? (@Lothiraldan)

**Comment by jberends** [comment]
as a horse...

**Comment by khaije1** [comment]
FWIW, https://github.com/martinhoefling/molten looks to be in good shape.

Just to strike a note of balance, if there were a many actively competing projects in this space I'm sure there would be calls to converge and deduplicate efforts.

**Comment by gee456** [comment]
I have tried to compile the project and cannot get past the npn dependency issues. .. FYI, the V1 is the only one that works, I finally got V2 to load but the minions are empty ... sad .. this was a nice project.

**Comment by grigorov** [comment]
I think project is dead... close issue
