### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by Lothiraldan** [Lothiraldan/saltpad#33]

**Comment by bbinet** [comment]
I was wondering about the status of this issue: how far is saltpad to be Python 3 compatible?

**Comment by Lothiraldan** [comment]
I think it should be almost completely compatible, just need to validate the support

**Comment by bbinet** [comment]
ok, thanks.

**Comment by Lothiraldan** [comment]
I just pushed a pull-request with some fixes for python 3.4, could you please give it a shot?
